/* eslint-disable @typescript-eslint/no-loss-of-precision */

import { RecipeInformation } from "./models/recipes/recipeInformation";

//Constants
export const API_URL = "https://api.spoonacular.com";
export const API_KEY = import.meta.env.VITE_SPOON_API_KEY; //API KEY FROM .env file

export const dataRecipe = {
  offset: 0,
  number: 2,
  results: [
    {
      id: 716429,
      title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
      image: "https://spoonacular.com/recipeImages/716429-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 715538,
      title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
      image: "https://spoonacular.com/recipeImages/715538-312x231.jpg",
      imageType: "jpg",
    },
  ],
  totalResults: 86,
};
//helper wait function to test out async tasks
export function wait(time: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, time);
  });
}

export const recipe_716429: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 16,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 209,
  healthScore: 18,
  creditsText: "Full Belly Sisters",
  license: "CC BY-SA 3.0",
  sourceName: "Full Belly Sisters",
  pricePerServing: 157.06,
  extendedIngredients: [
    {
      id: 1001,
      aisle: "Milk, Eggs, Other Dairy",
      image: "butter-sliced.jpg",
      consistency: "SOLID",
      name: "butter",
      nameClean: "butter",
      original: "1 tbsp butter",
      originalName: "butter",
      amount: 1.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 10011135,
      aisle: "Produce",
      image: "cauliflower.jpg",
      consistency: "SOLID",
      name: "cauliflower florets",
      nameClean: "cauliflower florets",
      original:
        "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
      originalName:
        "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
      amount: 2.0,
      unit: "cups",
      meta: ["frozen", "thawed", "cut into bite-sized pieces"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 200.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1038,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "SOLID",
      name: "cheese",
      nameClean: "pecorino romano",
      original: "2 tbsp grated cheese (I used romano)",
      originalName: "grated cheese (I used romano)",
      amount: 2.0,
      unit: "tbsp",
      meta: ["grated", "(I used romano)"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 1034053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "olive-oil.jpg",
      consistency: "LIQUID",
      name: "extra virgin olive oil",
      nameClean: "extra virgin olive oil",
      original: "1-2 tbsp extra virgin olive oil",
      originalName: "extra virgin olive oil",
      amount: 1.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "garlic.png",
      consistency: "SOLID",
      name: "garlic",
      nameClean: "garlic",
      original: "5-6 cloves garlic",
      originalName: "garlic",
      amount: 5.0,
      unit: "cloves",
      meta: [],
      measures: {
        us: {
          amount: 5.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
        metric: {
          amount: 5.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
      },
    },
    {
      id: 10720420,
      aisle: "Pasta and Rice",
      image: "spaghetti.jpg",
      consistency: "SOLID",
      name: "pasta",
      nameClean: "linguine",
      original: "6-8 ounces pasta (I used linguine)",
      originalName: "pasta (I used linguine)",
      amount: 6.0,
      unit: "ounces",
      meta: ["(I used linguine)"],
      measures: {
        us: {
          amount: 6.0,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 170.097,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1032009,
      aisle: "Spices and Seasonings",
      image: "red-pepper-flakes.jpg",
      consistency: "SOLID",
      name: "couple of pepper flakes",
      nameClean: "red pepper flakes",
      original: "couple of pinches red pepper flakes, optional",
      originalName: "couple of red pepper flakes, optional",
      amount: 2.0,
      unit: "pinches",
      meta: ["red"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "pinches",
          unitLong: "pinches",
        },
        metric: {
          amount: 2.0,
          unitShort: "pinches",
          unitLong: "pinches",
        },
      },
    },
    {
      id: 1102047,
      aisle: "Spices and Seasonings",
      image: "salt-and-pepper.jpg",
      consistency: "SOLID",
      name: "salt and pepper",
      nameClean: "salt and pepper",
      original: "salt and pepper, to taste",
      originalName: "salt and pepper, to taste",
      amount: 2.0,
      unit: "servings",
      meta: ["to taste"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 11291,
      aisle: "Produce",
      image: "spring-onions.jpg",
      consistency: "SOLID",
      name: "scallions",
      nameClean: "spring onions",
      original: "3 scallions, chopped, white and green parts separated",
      originalName: "scallions, chopped, white and green parts separated",
      amount: 3.0,
      unit: "",
      meta: ["white", "green", "separated", "chopped"],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 14106,
      aisle: "Alcoholic Beverages",
      image: "white-wine.jpg",
      consistency: "LIQUID",
      name: "white wine",
      nameClean: "dry white wine",
      original: "2-3 tbsp white wine",
      originalName: "white wine",
      amount: 2.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 99025,
      aisle: "Pasta and Rice",
      image: "breadcrumbs.jpg",
      consistency: "SOLID",
      name: "bread crumbs",
      nameClean: "whole wheat breadcrumbs",
      original: "1/4 cup whole wheat bread crumbs (I used panko)",
      originalName: "whole wheat bread crumbs (I used panko)",
      amount: 0.25,
      unit: "cup",
      meta: ["whole wheat", "(I used panko)"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 27.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 716429,
  title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
  readyInMinutes: 45,
  servings: 2,
  sourceUrl:
    "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
  image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
  imageType: "jpg",
  summary:
    'You can never have too many main course recipes, so give Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs a try. One serving contains <b>543 calories</b>, <b>17g of protein</b>, and <b>16g of fat</b>. For <b>$1.57 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. This recipe serves 2. A mixture of butter, white wine, pasta, and a handful of other ingredients are all it takes to make this recipe so yummy. 209 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 83%</b>, which is tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1230187">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229807">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229669">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>.',
  cuisines: [],
  dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
  diets: [],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText:
      "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
    productMatches: [],
  },
  instructions: "",
  analyzedInstructions: [],
  originalId: null,
  spoonacularScore: 83.37820434570312,
  spoonacularSourceUrl:
    "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
};

export const recipe_715538: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 15,
  gaps: "no",
  preparationMinutes: 5,
  cookingMinutes: 30,
  aggregateLikes: 163,
  healthScore: 27,
  creditsText: "pinkwhen.com",
  sourceName: "pinkwhen.com",
  pricePerServing: 195.54,
  extendedIngredients: [
    {
      id: 10120420,
      aisle: "Pasta and Rice",
      image: "farfalle.png",
      consistency: "SOLID",
      name: "bow tie pasta",
      nameClean: "farfalle",
      original: "3 cups bow tie pasta",
      originalName: "bow tie pasta",
      amount: 3.0,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 180.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1033,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "SOLID",
      name: "parmigiano reggiano",
      nameClean: "parmesan",
      original: "½ cup Parmigiano Reggiano",
      originalName: "Parmigiano Reggiano",
      amount: 0.5,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 50.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 20420,
      aisle: "Pasta and Rice",
      image: "fusilli.jpg",
      consistency: "SOLID",
      name: "recipe makers chicken bruschetta pasta",
      nameClean: "pasta",
      original: "Kraft Recipe Makers Chicken Bruschetta Pasta",
      originalName: "Kraft Recipe Makers Chicken Bruschetta Pasta",
      amount: 5.0,
      unit: "servings",
      meta: ["kraft"],
      measures: {
        us: {
          amount: 5.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 5.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 10010062,
      aisle: "Meat",
      image: "pork-chops.jpg",
      consistency: "SOLID",
      name: "pork chops",
      nameClean: "pork chops",
      original: "1-1/2 lb. pork chops",
      originalName: "pork chops",
      amount: 1.5,
      unit: "lb",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "lb",
          unitLong: "pounds",
        },
        metric: {
          amount: 680.389,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 715538,
  title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
  readyInMinutes: 35,
  servings: 5,
  sourceUrl: "http://www.pinkwhen.com/make-dinner-tonight/",
  image: "https://spoonacular.com/recipeImages/715538-556x370.jpg",
  imageType: "jpg",
  summary:
    'What to make for dinner tonight?? Bruschetta Style Pork & Pasta takes roughly <b>35 minutes</b> from beginning to end. This recipe serves 5 and costs $1.96 per serving. This main course has <b>591 calories</b>, <b>45g of protein</b>, and <b>13g of fat</b> per serving. If you have bow tie pasta, parmigiano reggiano, recipe makers chicken bruschetta pasta, and a few other ingredients on hand, you can make it. 163 people have made this recipe and would make it again. It is brought to you by Pink When. Plenty of people really liked this Mediterranean dish. With a spoonacular <b>score of 90%</b>, this dish is outstanding. Similar recipes are <a href="https://spoonacular.com/recipes/dinner-tonight-grilled-romesco-style-pork-209128">Dinner Tonight: Grilled Romesco-Style Pork</a>, <a href="https://spoonacular.com/recipes/dinner-tonight-chickpea-bruschetta-31868">Dinner Tonight: Chickpea Bruschetta</a>, and <a href="https://spoonacular.com/recipes/dinner-tonight-shrimp-bruschetta-from-da-zaccaria-209251">Dinner Tonight: Shrimp Bruschetta from \'da Zaccaria</a>.',
  cuisines: ["Mediterranean", "Italian", "European"],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: [],
  occasions: [],
  winePairing: {},
  instructions:
    "wash and rinse pork chops and place into the skillet.cut them into bite sized pieces and add half of the Basil Garlic simmer sauce.boil your water and start working on cooking your bow-tie pasta.when you have finished with boiling and draining your pasta, add it to the pork along with the rest of the Basil Garlic Simmering Sauce, mixing lightly.Next you will top with the Chunky Bruschetta Finishing Sauce, cover with Parmesan, and cover. Cooking on low heat 2 to 3 minutes or until heated through.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "wash and rinse pork chops and place into the skillet.cut them into bite sized pieces and add half of the Basil Garlic simmer sauce.boil your water and start working on cooking your bow-tie pasta.when you have finished with boiling and draining your pasta, add it to the pork along with the rest of the Basil Garlic Simmering Sauce, mixing lightly.Next you will top with the Chunky Bruschetta Finishing Sauce, cover with Parmesan, and cover. Cooking on low heat 2 to 3 minutes or until heated through.",
          ingredients: [
            {
              id: 10120420,
              name: "farfalle",
              localizedName: "farfalle",
              image: "farfalle.png",
            },
            {
              id: 10010062,
              name: "pork chops",
              localizedName: "pork chops",
              image: "pork-chops.jpg",
            },
            {
              id: 1033,
              name: "parmesan",
              localizedName: "parmesan",
              image: "parmesan.jpg",
            },
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
            {
              id: 2044,
              name: "basil",
              localizedName: "basil",
              image: "basil.jpg",
            },
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
            {
              id: 10010219,
              name: "pork",
              localizedName: "pork",
              image: "pork-tenderloin-raw.png",
            },
          ],
          equipment: [
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
          length: {
            number: 2,
            unit: "minutes",
          },
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 94.91596984863281,
  spoonacularSourceUrl:
    "https://spoonacular.com/what-to-make-for-dinner-tonight-bruschetta-style-pork-pasta-715538",
};
