/* eslint-disable @typescript-eslint/no-loss-of-precision */

import { RecipeInformation } from "./models/recipes/recipeInformation";

//Constants
export const API_URL = "https://api.spoonacular.com";
export const API_KEY = import.meta.env.VITE_SPOON_API_KEY; //API KEY FROM .env file

export const dataRecipe = {
  offset: 0,
  number: 2,
  results: [
    {
      id: 716429,
      title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
      image: "https://spoonacular.com/recipeImages/716429-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 715538,
      title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
      image: "https://spoonacular.com/recipeImages/715538-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654959,
      title: "Pasta With Tuna",
      image: "https://spoonacular.com/recipeImages/654959-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 511728,
      title: "Pasta Margherita",
      image: "https://spoonacular.com/recipeImages/511728-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654857,
      title: "Pasta On The Border",
      image: "https://spoonacular.com/recipeImages/654857-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654883,
      title: "Pasta Vegetable Soup",
      image: "https://spoonacular.com/recipeImages/654883-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654928,
      title: "Pasta With Italian Sausage",
      image: "https://spoonacular.com/recipeImages/654928-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654926,
      title: "Pasta With Gorgonzola Sauce",
      image: "https://spoonacular.com/recipeImages/654926-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654944,
      title: "Pasta With Salmon Cream Sauce",
      image: "https://spoonacular.com/recipeImages/654944-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654905,
      title: "Pasta With Chickpeas and Kale",
      image: "https://spoonacular.com/recipeImages/654905-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654901,
      title: "Pasta With Chicken and Broccoli",
      image: "https://spoonacular.com/recipeImages/654901-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654913,
      title: "Pasta With Chicken and Mushrooms",
      image: "https://spoonacular.com/recipeImages/654913-312x231.jpg",
      imageType: "jpg",
    },
  ],
  totalResults: 86,
};
export const dataRecipePizza = {
  results: [
    {
      id: 656329,
      title: "Pizza bites with pumpkin",
      image: "https://spoonacular.com/recipeImages/656329-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 680975,
      title: "BLT Pizza",
      image: "https://spoonacular.com/recipeImages/680975-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 663136,
      title: "Thai Pizza",
      image: "https://spoonacular.com/recipeImages/663136-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716300,
      title: "Plantain Pizza",
      image: "https://spoonacular.com/recipeImages/716300-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 665769,
      title: "Zucchini Pizza Boats",
      image: "https://spoonacular.com/recipeImages/665769-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 655698,
      title: "Pepperoni Pizza Muffins",
      image: "https://spoonacular.com/recipeImages/655698-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 622598,
      title: "Pittata - Pizza Frittata",
      image: "https://spoonacular.com/recipeImages/622598-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 641893,
      title: "Easy Cheesy Pizza Casserole",
      image: "https://spoonacular.com/recipeImages/641893-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654523,
      title: "Paneer & Fig Pizza",
      image: "https://spoonacular.com/recipeImages/654523-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 655847,
      title: "Pesto Veggie Pizza",
      image: "https://spoonacular.com/recipeImages/655847-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 0,
  number: 10,
  totalResults: 35,
};
export const dataRecipePancake = {
  results: [
    {
      id: 654485,
      title: "Pancake Bites",
      image: "https://spoonacular.com/recipeImages/654485-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654487,
      title: "Pancake Cupcakes With Maple Frosting and Candied Bacon",
      image: "https://spoonacular.com/recipeImages/654487-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 653472,
      title: "Oatmeal Pancake (Yummy & Heart Healthy)",
      image: "https://spoonacular.com/recipeImages/653472-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 633428,
      title: "Baked Apple Pancake",
      image: "https://spoonacular.com/recipeImages/633428-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 633830,
      title: "Baked Swedish Pancake",
      image: "https://spoonacular.com/recipeImages/633830-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 662582,
      title: "Sweet Potato Green Tea Pancake Roll",
      image: "https://spoonacular.com/recipeImages/662582-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 716269,
      title: "Peach Carrot Coconut Vegan Pancake",
      image: "https://spoonacular.com/recipeImages/716269-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 654495,
      title: "Pancakes",
      image: "https://spoonacular.com/recipeImages/654495-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 756817,
      title: "Matcha Pancakes",
      image: "https://spoonacular.com/recipeImages/756817-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 635001,
      title: "Birthday Pancakes",
      image: "https://spoonacular.com/recipeImages/635001-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 0,
  number: 10,
  totalResults: 66,
};

//helper wait function to test out async tasks
export function wait(time: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, time);
  });
}

export const recipe_716429: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 16,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 209,
  healthScore: 18,
  creditsText: "Full Belly Sisters",
  license: "CC BY-SA 3.0",
  sourceName: "Full Belly Sisters",
  pricePerServing: 157.06,
  extendedIngredients: [
    {
      id: 1001,
      aisle: "Milk, Eggs, Other Dairy",
      image: "butter-sliced.jpg",
      consistency: "SOLID",
      name: "butter",
      nameClean: "butter",
      original: "1 tbsp butter",
      originalName: "butter",
      amount: 1.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 10011135,
      aisle: "Produce",
      image: "cauliflower.jpg",
      consistency: "SOLID",
      name: "cauliflower florets",
      nameClean: "cauliflower florets",
      original:
        "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
      originalName:
        "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
      amount: 2.0,
      unit: "cups",
      meta: ["frozen", "thawed", "cut into bite-sized pieces"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 200.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1038,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "SOLID",
      name: "cheese",
      nameClean: "pecorino romano",
      original: "2 tbsp grated cheese (I used romano)",
      originalName: "grated cheese (I used romano)",
      amount: 2.0,
      unit: "tbsp",
      meta: ["grated", "(I used romano)"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 1034053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "olive-oil.jpg",
      consistency: "LIQUID",
      name: "extra virgin olive oil",
      nameClean: "extra virgin olive oil",
      original: "1-2 tbsp extra virgin olive oil",
      originalName: "extra virgin olive oil",
      amount: 1.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "garlic.png",
      consistency: "SOLID",
      name: "garlic",
      nameClean: "garlic",
      original: "5-6 cloves garlic",
      originalName: "garlic",
      amount: 5.0,
      unit: "cloves",
      meta: [],
      measures: {
        us: {
          amount: 5.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
        metric: {
          amount: 5.0,
          unitShort: "cloves",
          unitLong: "cloves",
        },
      },
    },
    {
      id: 10720420,
      aisle: "Pasta and Rice",
      image: "spaghetti.jpg",
      consistency: "SOLID",
      name: "pasta",
      nameClean: "linguine",
      original: "6-8 ounces pasta (I used linguine)",
      originalName: "pasta (I used linguine)",
      amount: 6.0,
      unit: "ounces",
      meta: ["(I used linguine)"],
      measures: {
        us: {
          amount: 6.0,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 170.097,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1032009,
      aisle: "Spices and Seasonings",
      image: "red-pepper-flakes.jpg",
      consistency: "SOLID",
      name: "couple of pepper flakes",
      nameClean: "red pepper flakes",
      original: "couple of pinches red pepper flakes, optional",
      originalName: "couple of red pepper flakes, optional",
      amount: 2.0,
      unit: "pinches",
      meta: ["red"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "pinches",
          unitLong: "pinches",
        },
        metric: {
          amount: 2.0,
          unitShort: "pinches",
          unitLong: "pinches",
        },
      },
    },
    {
      id: 1102047,
      aisle: "Spices and Seasonings",
      image: "salt-and-pepper.jpg",
      consistency: "SOLID",
      name: "salt and pepper",
      nameClean: "salt and pepper",
      original: "salt and pepper, to taste",
      originalName: "salt and pepper, to taste",
      amount: 2.0,
      unit: "servings",
      meta: ["to taste"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 2.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 11291,
      aisle: "Produce",
      image: "spring-onions.jpg",
      consistency: "SOLID",
      name: "scallions",
      nameClean: "spring onions",
      original: "3 scallions, chopped, white and green parts separated",
      originalName: "scallions, chopped, white and green parts separated",
      amount: 3.0,
      unit: "",
      meta: ["white", "green", "separated", "chopped"],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 3.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 14106,
      aisle: "Alcoholic Beverages",
      image: "white-wine.jpg",
      consistency: "LIQUID",
      name: "white wine",
      nameClean: "dry white wine",
      original: "2-3 tbsp white wine",
      originalName: "white wine",
      amount: 2.0,
      unit: "tbsp",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 99025,
      aisle: "Pasta and Rice",
      image: "breadcrumbs.jpg",
      consistency: "SOLID",
      name: "bread crumbs",
      nameClean: "whole wheat breadcrumbs",
      original: "1/4 cup whole wheat bread crumbs (I used panko)",
      originalName: "whole wheat bread crumbs (I used panko)",
      amount: 0.25,
      unit: "cup",
      meta: ["whole wheat", "(I used panko)"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 27.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 716429,
  title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
  readyInMinutes: 45,
  servings: 2,
  sourceUrl:
    "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
  image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
  imageType: "jpg",
  summary:
    'You can never have too many main course recipes, so give Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs a try. One serving contains <b>543 calories</b>, <b>17g of protein</b>, and <b>16g of fat</b>. For <b>$1.57 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. This recipe serves 2. A mixture of butter, white wine, pasta, and a handful of other ingredients are all it takes to make this recipe so yummy. 209 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 83%</b>, which is tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1230187">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229807">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229669">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>.',
  cuisines: [],
  dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
  diets: [],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText:
      "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
    productMatches: [],
  },
  instructions: "",
  analyzedInstructions: [],
  originalId: null,
  spoonacularScore: 83.37820434570312,
  spoonacularSourceUrl:
    "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
};

export const recipe_715538: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 15,
  gaps: "no",
  preparationMinutes: 5,
  cookingMinutes: 30,
  aggregateLikes: 163,
  healthScore: 27,
  creditsText: "pinkwhen.com",
  sourceName: "pinkwhen.com",
  pricePerServing: 195.54,
  extendedIngredients: [
    {
      id: 10120420,
      aisle: "Pasta and Rice",
      image: "farfalle.png",
      consistency: "SOLID",
      name: "bow tie pasta",
      nameClean: "farfalle",
      original: "3 cups bow tie pasta",
      originalName: "bow tie pasta",
      amount: 3.0,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 180.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1033,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "SOLID",
      name: "parmigiano reggiano",
      nameClean: "parmesan",
      original: "½ cup Parmigiano Reggiano",
      originalName: "Parmigiano Reggiano",
      amount: 0.5,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 50.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 20420,
      aisle: "Pasta and Rice",
      image: "fusilli.jpg",
      consistency: "SOLID",
      name: "recipe makers chicken bruschetta pasta",
      nameClean: "pasta",
      original: "Kraft Recipe Makers Chicken Bruschetta Pasta",
      originalName: "Kraft Recipe Makers Chicken Bruschetta Pasta",
      amount: 5.0,
      unit: "servings",
      meta: ["kraft"],
      measures: {
        us: {
          amount: 5.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 5.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 10010062,
      aisle: "Meat",
      image: "pork-chops.jpg",
      consistency: "SOLID",
      name: "pork chops",
      nameClean: "pork chops",
      original: "1-1/2 lb. pork chops",
      originalName: "pork chops",
      amount: 1.5,
      unit: "lb",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "lb",
          unitLong: "pounds",
        },
        metric: {
          amount: 680.389,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 715538,
  title: "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
  readyInMinutes: 35,
  servings: 5,
  sourceUrl: "http://www.pinkwhen.com/make-dinner-tonight/",
  image: "https://spoonacular.com/recipeImages/715538-556x370.jpg",
  imageType: "jpg",
  summary:
    'What to make for dinner tonight?? Bruschetta Style Pork & Pasta takes roughly <b>35 minutes</b> from beginning to end. This recipe serves 5 and costs $1.96 per serving. This main course has <b>591 calories</b>, <b>45g of protein</b>, and <b>13g of fat</b> per serving. If you have bow tie pasta, parmigiano reggiano, recipe makers chicken bruschetta pasta, and a few other ingredients on hand, you can make it. 163 people have made this recipe and would make it again. It is brought to you by Pink When. Plenty of people really liked this Mediterranean dish. With a spoonacular <b>score of 90%</b>, this dish is outstanding. Similar recipes are <a href="https://spoonacular.com/recipes/dinner-tonight-grilled-romesco-style-pork-209128">Dinner Tonight: Grilled Romesco-Style Pork</a>, <a href="https://spoonacular.com/recipes/dinner-tonight-chickpea-bruschetta-31868">Dinner Tonight: Chickpea Bruschetta</a>, and <a href="https://spoonacular.com/recipes/dinner-tonight-shrimp-bruschetta-from-da-zaccaria-209251">Dinner Tonight: Shrimp Bruschetta from \'da Zaccaria</a>.',
  cuisines: ["Mediterranean", "Italian", "European"],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: [],
  occasions: [],
  winePairing: {},
  instructions:
    "wash and rinse pork chops and place into the skillet.cut them into bite sized pieces and add half of the Basil Garlic simmer sauce.boil your water and start working on cooking your bow-tie pasta.when you have finished with boiling and draining your pasta, add it to the pork along with the rest of the Basil Garlic Simmering Sauce, mixing lightly.Next you will top with the Chunky Bruschetta Finishing Sauce, cover with Parmesan, and cover. Cooking on low heat 2 to 3 minutes or until heated through.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "wash and rinse pork chops and place into the skillet.cut them into bite sized pieces and add half of the Basil Garlic simmer sauce.boil your water and start working on cooking your bow-tie pasta.when you have finished with boiling and draining your pasta, add it to the pork along with the rest of the Basil Garlic Simmering Sauce, mixing lightly.Next you will top with the Chunky Bruschetta Finishing Sauce, cover with Parmesan, and cover. Cooking on low heat 2 to 3 minutes or until heated through.",
          ingredients: [
            {
              id: 10120420,
              name: "farfalle",
              localizedName: "farfalle",
              image: "farfalle.png",
            },
            {
              id: 10010062,
              name: "pork chops",
              localizedName: "pork chops",
              image: "pork-chops.jpg",
            },
            {
              id: 1033,
              name: "parmesan",
              localizedName: "parmesan",
              image: "parmesan.jpg",
            },
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
            {
              id: 2044,
              name: "basil",
              localizedName: "basil",
              image: "basil.jpg",
            },
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
            {
              id: 10010219,
              name: "pork",
              localizedName: "pork",
              image: "pork-tenderloin-raw.png",
            },
          ],
          equipment: [
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
          length: {
            number: 2,
            unit: "minutes",
          },
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 94.91596984863281,
  spoonacularSourceUrl:
    "https://spoonacular.com/what-to-make-for-dinner-tonight-bruschetta-style-pork-pasta-715538",
};

export const recipe_654959: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: true,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 11,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 2,
  healthScore: 90,
  creditsText: "foodista.com",
  sourceName: "foodista.com",
  pricePerServing: 168.12,
  extendedIngredients: [
    {
      id: 20081,
      aisle: "Baking",
      image: "flour.png",
      consistency: "SOLID",
      name: "flour",
      nameClean: "wheat flour",
      original: "2 tablespoons Flour",
      originalName: "Flour",
      amount: 2.0,
      unit: "tablespoons",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 11291,
      aisle: "Produce",
      image: "spring-onions.jpg",
      consistency: "SOLID",
      name: "green onions",
      nameClean: "spring onions",
      original: "cup Green Onions, chopped",
      originalName: "Green Onions, chopped",
      amount: 1.0,
      unit: "cup",
      meta: ["chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 100.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1085,
      aisle: "Milk, Eggs, Other Dairy",
      image: "milk.jpg",
      consistency: "LIQUID",
      name: "non-fat milk",
      nameClean: "fat free milk",
      original: "1 1/4 cups Non-Fat Milk",
      originalName: "Non-Fat Milk",
      amount: 1.25,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 1.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 306.25,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 4053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "olive-oil.jpg",
      consistency: "SOLID",
      name: "olive oil",
      nameClean: "olive oil",
      original: "2 tablespoons Olive Oil",
      originalName: "Olive Oil",
      amount: 2.0,
      unit: "tablespoons",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 11282,
      aisle: "Produce",
      image: "brown-onion.png",
      consistency: "SOLID",
      name: "onion",
      nameClean: "onion",
      original: "2 tablespoons Onion, minced",
      originalName: "Onion, minced",
      amount: 2.0,
      unit: "tablespoons",
      meta: ["minced"],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2.0,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 1033,
      aisle: "Cheese",
      image: "parmesan.jpg",
      consistency: "SOLID",
      name: "parmesan cheese",
      nameClean: "parmesan",
      original: "1/4 cup Parmesan Cheese, grated",
      originalName: "Parmesan Cheese, grated",
      amount: 0.25,
      unit: "cup",
      meta: ["grated"],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 25.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 10511297,
      aisle: "Produce",
      image: "parsley.jpg",
      consistency: "SOLID",
      name: "parsley",
      nameClean: "fresh parsley",
      original: "cup Fresh Parsley or Basil, chopped",
      originalName: "Fresh Parsley or Basil, chopped",
      amount: 1.0,
      unit: "cup",
      meta: ["fresh", "chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 60.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 20420,
      aisle: "Pasta and Rice",
      image: "fusilli.jpg",
      consistency: "SOLID",
      name: "tubular pasta",
      nameClean: "pasta",
      original: "8 ounces Tubular Pasta",
      originalName: "Tubular Pasta",
      amount: 8.0,
      unit: "ounces",
      meta: [],
      measures: {
        us: {
          amount: 8.0,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 226.796,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 11304,
      aisle: "Produce",
      image: "peas.jpg",
      consistency: "SOLID",
      name: "peas",
      nameClean: "petite peas",
      original: "1 cup Frozen Peas, thawed",
      originalName: "Frozen Peas, thawed",
      amount: 1.0,
      unit: "cup",
      meta: ["frozen", "thawed"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 145.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 6168,
      aisle: "Condiments",
      image: "hot-sauce-or-tabasco.png",
      consistency: "LIQUID",
      name: "dsh pepper sauce",
      nameClean: "hot sauce",
      original: "1 dsh Hot Pepper Sauce",
      originalName: "dsh Hot Pepper Sauce",
      amount: 1.0,
      unit: "",
      meta: ["hot"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 15121,
      aisle: "Canned and Jarred",
      image: "canned-tuna.png",
      consistency: "SOLID",
      name: "water-packed tuna",
      nameClean: "tuna packed in water",
      original: "6 1/2 ounces Can Water-Packed Tuna, drained",
      originalName: "Water-Packed Tuna, drained",
      amount: 6.5,
      unit: "ounces",
      meta: ["drained"],
      measures: {
        us: {
          amount: 6.5,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 184.272,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
  ],
  id: 654959,
  title: "Pasta With Tuna",
  readyInMinutes: 45,
  servings: 4,
  sourceUrl: "http://www.foodista.com/recipe/K6QWSKQM/pasta-with-tuna",
  image: "https://spoonacular.com/recipeImages/654959-556x370.jpg",
  imageType: "jpg",
  summary:
    'Pasta With Tunan is a <b>pescatarian</b> main course. This recipe serves 4. For <b>$1.68 per serving</b>, this recipe <b>covers 28%</b> of your daily requirements of vitamins and minerals. One serving contains <b>423 calories</b>, <b>24g of protein</b>, and <b>10g of fat</b>. 2 people have made this recipe and would make it again. This recipe from Foodista requires flour, parsley, non-fat milk, and parmesan cheese. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 92%</b>. This score is amazing. <a href="https://spoonacular.com/recipes/pasta-and-tuna-salad-ensalada-de-pasta-y-atn-226303">Pastan and Tuna Salad (Ensalada de Pasta y Atún)</a>, <a href="https://spoonacular.com/recipes/tuna-pasta-565100">Tuna Pasta</a>, and <a href="https://spoonacular.com/recipes/tuna-pasta-89136">Tuna Pasta</a> are very similar to this recipe.',
  cuisines: [],
  dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
  diets: ["pescatarian"],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText:
      "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
    productMatches: [],
  },
  instructions:
    "<ol><li>Cook pasta in a large pot of boiling water until al dente. Drain and return to warm pot. Put olive oil in saucepan and add onion. Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens. Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce. Pour over pasta and stir gently to mix. Serve at once.</li></ol>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Cook pasta in a large pot of boiling water until al dente.",
          ingredients: [
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
          ],
          equipment: [
            {
              id: 404752,
              name: "pot",
              localizedName: "pot",
              image: "stock-pot.jpg",
            },
          ],
        },
        {
          number: 2,
          step: "Drain and return to warm pot. Put olive oil in saucepan and add onion.",
          ingredients: [
            {
              id: 4053,
              name: "olive oil",
              localizedName: "olive oil",
              image: "olive-oil.jpg",
            },
            {
              id: 11282,
              name: "onion",
              localizedName: "onion",
              image: "brown-onion.png",
            },
          ],
          equipment: [
            {
              id: 404669,
              name: "sauce pan",
              localizedName: "sauce pan",
              image: "sauce-pan.jpg",
            },
            {
              id: 404752,
              name: "pot",
              localizedName: "pot",
              image: "stock-pot.jpg",
            },
          ],
        },
        {
          number: 3,
          step: "Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens.",
          ingredients: [
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
            {
              id: 1077,
              name: "milk",
              localizedName: "milk",
              image: "milk.png",
            },
          ],
          equipment: [
            {
              id: 404661,
              name: "whisk",
              localizedName: "whisk",
              image: "whisk.png",
            },
          ],
        },
        {
          number: 4,
          step: "Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce.",
          ingredients: [
            {
              id: 6168,
              name: "hot sauce",
              localizedName: "hot sauce",
              image: "hot-sauce-or-tabasco.png",
            },
            {
              id: 11291,
              name: "green onions",
              localizedName: "green onions",
              image: "spring-onions.jpg",
            },
            {
              id: 11297,
              name: "parsley",
              localizedName: "parsley",
              image: "parsley.jpg",
            },
            {
              id: 1041009,
              name: "cheese",
              localizedName: "cheese",
              image: "cheddar-cheese.png",
            },
            {
              id: 11304,
              name: "peas",
              localizedName: "peas",
              image: "peas.jpg",
            },
            {
              id: 10015121,
              name: "tuna",
              localizedName: "tuna",
              image: "canned-tuna.png",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Pour over pasta and stir gently to mix.",
          ingredients: [
            {
              id: 20420,
              name: "pasta",
              localizedName: "pasta",
              image: "fusilli.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 6,
          step: "Serve at once.",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 93.85128021240234,
  spoonacularSourceUrl: "https://spoonacular.com/pasta-with-tuna-654959",
};

export const recipe_716300: RecipeInformation = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 16,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 95,
  healthScore: 29,
  creditsText: "afrolems.com",
  sourceName: "afrolems.com",
  pricePerServing: 146.54,
  extendedIngredients: [
    {
      id: 23572,
      aisle: "Frozen",
      image: "beef-cubes-raw.png",
      consistency: "SOLID",
      name: "beef",
      nameClean: "beef",
      original: "1 cup of chopped Beef",
      originalName: "chopped Beef",
      amount: 1.0,
      unit: "cup",
      meta: ["chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "cup",
          unitLong: "cup",
        },
        metric: {
          amount: 225.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 10211821,
      aisle: "Produce",
      image: "yellow-bell-pepper.jpg",
      consistency: "SOLID",
      name: "bell pepper",
      nameClean: "bell pepper",
      original: "1 Bell pepper (Blended)",
      originalName: "Bell pepper (Blended)",
      amount: 1.0,
      unit: "",
      meta: ["(Blended)"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 10211821,
      aisle: "Produce",
      image: "bell-pepper-orange.png",
      consistency: "SOLID",
      name: "bell pepper",
      nameClean: "bell pepper",
      original: "1 Bell pepper (Blended)",
      originalName: "Bell pepper (Blended)",
      amount: 1.0,
      unit: "",
      meta: ["(Blended)"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 10211821,
      aisle: "Produce",
      image: "bell-pepper-orange.png",
      consistency: "SOLID",
      name: "bell peppers",
      nameClean: "bell pepper",
      original: "1 handful of chopped bell peppers",
      originalName: "chopped bell peppers",
      amount: 1.0,
      unit: "handful",
      meta: ["chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
        metric: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
      },
    },
    {
      id: 10211821,
      aisle: "Produce",
      image: "yellow-bell-pepper.jpg",
      consistency: "SOLID",
      name: "bell peppers",
      nameClean: "bell pepper",
      original: "1 handful of chopped bell peppers",
      originalName: "chopped bell peppers",
      amount: 1.0,
      unit: "handful",
      meta: ["chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
        metric: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
      },
    },
    {
      id: 10120129,
      aisle: "Baking",
      image: "flour.png",
      consistency: "SOLID",
      name: "bread flour",
      nameClean: "bread flour",
      original: "2 cups of Bread flour",
      originalName: "Bread flour",
      amount: 2.0,
      unit: "cups",
      meta: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 250.0,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 10014412,
      aisle: "Frozen",
      image: "ice-cubes.png",
      consistency: "SOLID",
      name: "seasoning cube",
      nameClean: "ice",
      original: "Seasoning cube",
      originalName: "Seasoning cube",
      amount: 3.0,
      unit: "servings",
      meta: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 3.0,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 4582,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "vegetable-oil.jpg",
      consistency: "LIQUID",
      name: "oil",
      nameClean: "cooking oil",
      original: "1 tablespoon of oil",
      originalName: "oil",
      amount: 1.0,
      unit: "tablespoon",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1.0,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 4582,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "vegetable-oil.jpg",
      consistency: "LIQUID",
      name: "oil",
      nameClean: "cooking oil",
      original: "1 teaspoon oil",
      originalName: "oil",
      amount: 1.0,
      unit: "teaspoon",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
        metric: {
          amount: 1.0,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
      },
    },
    {
      id: 11282,
      aisle: "Produce",
      image: "brown-onion.png",
      consistency: "SOLID",
      name: "onions",
      nameClean: "onion",
      original: "A handful of chopped onions",
      originalName: "chopped onions",
      amount: 1.0,
      unit: "handful",
      meta: ["chopped"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
        metric: {
          amount: 1.0,
          unitShort: "handful",
          unitLong: "handful",
        },
      },
    },
    {
      id: 10099295,
      aisle: "Produce",
      image: "bananas-ripe.jpg",
      consistency: "SOLID",
      name: "over-ripe plantain",
      nameClean: "yellow plantain",
      original: "1 over-ripe plantain (Mashed)",
      originalName: "over-ripe plantain (Mashed)",
      amount: 1.0,
      unit: "",
      meta: ["mashed", "()"],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "SOLID",
      name: "salt",
      nameClean: "table salt",
      original: "1 teaspoon salt",
      originalName: "salt",
      amount: 1.0,
      unit: "teaspoon",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
        metric: {
          amount: 1.0,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
      },
    },
    {
      id: 19335,
      aisle: "Baking",
      image: "sugar-in-bowl.png",
      consistency: "SOLID",
      name: "sugar",
      nameClean: "sugar",
      original: "1/2 teaspoon of sugar",
      originalName: "sugar",
      amount: 0.5,
      unit: "teaspoon",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 11529,
      aisle: "Produce",
      image: "tomato.png",
      consistency: "SOLID",
      name: "tomato)",
      nameClean: "tomato",
      original: "1 tomato(Blended)",
      originalName: "tomato(Blended)",
      amount: 1.0,
      unit: "",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1.0,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 14412,
      aisle: "Beverages",
      image: "water.png",
      consistency: "LIQUID",
      name: "water",
      nameClean: "water",
      original: "3/4 cup of water",
      originalName: "water",
      amount: 0.75,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.75,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 177.441,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 18375,
      aisle: "Baking",
      image: "yeast-granules.jpg",
      consistency: "SOLID",
      name: "yeast",
      nameClean: "dry yeast",
      original: "1.5 teaspoons of yeast",
      originalName: "yeast",
      amount: 1.5,
      unit: "teaspoons",
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 1.5,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
  ],
  id: 716300,
  title: "Plantain Pizza",
  readyInMinutes: 45,
  servings: 3,
  sourceUrl: "http://www.afrolems.com/2014/03/08/plantain-pizza/",
  image: "https://spoonacular.com/recipeImages/716300-556x370.jpg",
  imageType: "jpg",
  summary:
    'Plantain Pizzan is a Mediterranean main course. One serving contains <b>657 calories</b>, <b>27g of protein</b>, and <b>23g of fat</b>. This dairy free recipe serves 3 and costs <b>$1.47 per serving</b>. 95 people were impressed by this recipe. It is brought to you by Afrolems. If you have tomato), bell pepper, bell peppers, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 91%</b>. This score is outstanding. Similar recipes include <a href="https://spoonacular.com/recipes/how-to-spiralize-a-plantain-plantain-rice-and-beans-563745">How to Spiralize a Plantain & Plantain “Rice” and Beans</a>, <a href="https://spoonacular.com/recipes/plantain-chips-150821">Plantain Chips</a>, and <a href="https://spoonacular.com/recipes/plantain-fritters-316444">Plantain Fritters</a>.',
  cuisines: ["Mediterranean", "Italian", "European"],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["dairy free"],
  occasions: [],
  winePairing: {
    pairedWines: ["sangiovese", "shiraz", "barbera wine"],
    pairingText:
      "Sangiovese, Shiraz, and Barbera Wine are great choices for Pizza. The best wine for pizza depends on the toppings! Red sauce pizza will call for a red wine with some acidity, such as a barberan or sangiovese. Add pepperoni or sausage and you can go bolder with a syrah. One wine you could try is Antinori Villan Antinori Chianti Classico Riserva. It has 4.6 out of 5 stars and a bottle costs about 36 dollars.",
    productMatches: [
      {
        id: 434818,
        title: "Antinori Villa Antinori Chianti Classico Riserva",
        description:
          "Crafted from 90% Sangiovese and 10% Merlot, the 2010 Villa Antinori Chianti Classico Riserva is intense ruby red in color with fruit and spice aromas. Light touches from the oak aging underscore the cherry and red berry notes that are typical of the Sangiovese grape. The wine's flavors are harmonious on the palate with tannins that are balanced and ripe. The lingering finish is vibrant with a pleasing minerality, which is typical of Chianti Classico.",
        price: "$35.9900016784668",
        imageUrl: "https://spoonacular.com/productImages/434818-312x231.jpg",
        averageRating: 0.9200000166893005,
        ratingCount: 5.0,
        score: 0.8575000166893005,
        link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fantinori-villa-antinori-chianti-classico-riserva-2010%2F122374",
      },
    ],
  },
  instructions:
    "<p>Dissolve the yeast in warm water and leave to stand for about 5 minutes.Mix the oil, flour, salt, sugar and mashed plantain and pour in the dissolved yeast.Knead the dough till its elastic which may take aBout 15-20 minutes By hand or 10 minutes in a mixer.Coat a Bowl lightly with oil and place the dough in it. Cover with a plastic wrap and leave to rise between 1.5 – 2 hours.While the dough is rising, heat up the oil for the sauce, fry the Blended tomato and pepper, season and stir fry the Beef in the tomato sauce. Set aside.When the dough rises, divide into two. Sprinkle some flour on a flat surface and with a rolling pin, flatten out the dough but not excessively. Cut the dough into your desired shape, rub some oil on it and spread your sauce and toppings on it and set aside.Heat up your oven to 350 F and place your pizza dough on a lightly oiled foil pan and Bake for 12-15 mins. Serve warm</p>",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Dissolve the yeast in warm water and leave to stand for about 5 minutes.",
          ingredients: [
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
            {
              id: 18375,
              name: "yeast",
              localizedName: "yeast",
              image: "yeast-granules.jpg",
            },
          ],
          equipment: [],
          length: {
            number: 5,
            unit: "minutes",
          },
        },
        {
          number: 2,
          step: "Mix the oil, flour, salt, sugar and mashed plantain and pour in the dissolved yeast.Knead the dough till its elastic which may take aBout 15-20 minutes By hand or 10 minutes in a mixer.Coat a Bowl lightly with oil and place the dough in it. Cover with a plastic wrap and leave to rise between 1.5 – 2 hours.While the dough is rising, heat up the oil for the sauce, fry the Blended tomato and pepper, season and stir fry the Beef in the tomato sauce. Set aside.When the dough rises, divide into two.",
          ingredients: [
            {
              id: 11549,
              name: "tomato sauce",
              localizedName: "tomato sauce",
              image: "tomato-sauce-or-pasta-sauce.jpg",
            },
            {
              id: 99295,
              name: "plantain",
              localizedName: "plantain",
              image: "plantains.jpg",
            },
            {
              id: 1002030,
              name: "pepper",
              localizedName: "pepper",
              image: "pepper.jpg",
            },
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
            {
              id: 0,
              name: "dough",
              localizedName: "dough",
              image: "pizza-dough",
            },
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 19335,
              name: "sugar",
              localizedName: "sugar",
              image: "sugar-in-bowl.png",
            },
            {
              id: 18375,
              name: "yeast",
              localizedName: "yeast",
              image: "yeast-granules.jpg",
            },
            {
              id: 23572,
              name: "beef",
              localizedName: "beef",
              image: "beef-cubes-raw.png",
            },
            {
              id: 2047,
              name: "salt",
              localizedName: "salt",
              image: "salt.jpg",
            },
            {
              id: 10018364,
              name: "wrap",
              localizedName: "wrap",
              image: "flour-tortilla.jpg",
            },
            {
              id: 4582,
              name: "cooking oil",
              localizedName: "cooking oil",
              image: "vegetable-oil.jpg",
            },
          ],
          equipment: [
            {
              id: 404730,
              name: "plastic wrap",
              localizedName: "plastic wrap",
              image: "plastic-wrap.jpg",
            },
            {
              id: 404726,
              name: "blender",
              localizedName: "blender",
              image: "blender.png",
            },
            {
              id: 404783,
              name: "bowl",
              localizedName: "bowl",
              image: "bowl.jpg",
            },
          ],
          length: {
            number: 150,
            unit: "minutes",
          },
        },
        {
          number: 3,
          step: "Sprinkle some flour on a flat surface and with a rolling pin, flatten out the dough but not excessively.",
          ingredients: [
            {
              id: 0,
              name: "dough",
              localizedName: "dough",
              image: "pizza-dough",
            },
            {
              id: 20081,
              name: "all purpose flour",
              localizedName: "all purpose flour",
              image: "flour.png",
            },
          ],
          equipment: [
            {
              id: 404746,
              name: "rolling pin",
              localizedName: "rolling pin",
              image: "rolling-pin.jpg",
            },
          ],
        },
        {
          number: 4,
          step: "Cut the dough into your desired shape, rub some oil on it and spread your sauce and toppings on it and set aside.",
          ingredients: [
            {
              id: 0,
              name: "spread",
              localizedName: "spread",
              image: "",
            },
            {
              id: 0,
              name: "dough",
              localizedName: "dough",
              image: "pizza-dough",
            },
            {
              id: 0,
              name: "sauce",
              localizedName: "sauce",
              image: "",
            },
            {
              id: 4582,
              name: "cooking oil",
              localizedName: "cooking oil",
              image: "vegetable-oil.jpg",
            },
            {
              id: 1012034,
              name: "dry seasoning rub",
              localizedName: "dry seasoning rub",
              image: "seasoning.png",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Heat up your oven to 350 F and place your pizza dough on a lightly oiled foil pan and",
          ingredients: [
            {
              id: 93610,
              name: "pizza dough",
              localizedName: "pizza dough",
              image: "pizza-dough.jpg",
            },
          ],
          equipment: [
            {
              id: 404765,
              name: "aluminum foil",
              localizedName: "aluminum foil",
              image: "aluminum-foil.png",
            },
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "oven.jpg",
              temperature: {
                number: 350.0,
                unit: "Fahrenheit",
              },
            },
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 6,
          step: "Bake for 12-15 mins.",
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "oven.jpg",
            },
          ],
          length: {
            number: 15,
            unit: "minutes",
          },
        },
        {
          number: 7,
          step: "Serve warm",
          ingredients: [],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 91.97254180908203,
  spoonacularSourceUrl: "https://spoonacular.com/plantain-pizza-716300",
};
